services:
  web: 
    build: ./web-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=development
    volumes:
      - ./web-app:/app

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ml-client:
    build:
      context: ./machine-learning-client
    container_name: ml-client
    depends_on:
      - mongodb
    volumes:
      - ./machine-learning-client/static:/app/static
    environment:
      - MONGO_URI=mongodb://mongodb:27017

volumes:
  mongo-data: