services:
  web: 
    build: ./web-app
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
      - ml-client
    environment:
      - FLASK_ENV=development
    volumes:
      - ./web-app:/app

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ml-client:
    build:
      context: ./machine-learning-client
    ports:
      - "8000:8000"
    container_name: ml-client
    depends_on:
      - mongodb
    volumes:
      - ./machine-learning-client/static:/app/static
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017

volumes:
  mongo-data: