name: ML client testing
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9"]

    defaults:
      run:
        working-directory: machine-learning-client

    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          pipenv install pytest coverage

      - name: Run tests and coverage
        run: |
          pipenv run coverage run -m pytest
          pipenv run coverage report --fail-under=80
